[versions]
minSdk = "26"
targetSdk = "35"
compileSdk = "35"
composeBom = "2024.11.00"
activityCompose = "1.9.3"
coreKtx = "1.15.0"
hiltAndroid = "2.52"
hiltNavigationCompose = "1.2.0"
junitJupiter = "5.10.2"
kotest = "5.8.1"
mock = "1.13.12"
androidxLifecycle = "2.8.7"
navigationCompose = "2.8.4"
roomVersion = "2.6.1"
coroutinesTest = "1.9.0"
serialization = "1.7.3"

androidGradlePlugin = "8.7.3"
kotlinPlugin = "2.0.20"
hiltPlugin = "2.52"
kspPlugin = "2.0.20-1.0.25"
ktlintPlugin = "12.1.1"
ktlintGradlePlugin = "12.1.1"
uiTooling = "1.7.5"


[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" } #Access composable APIs built on top of Activity.
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" } # Fundamental components of compose UI needed to interact with the device, including layout, drawing, and input.
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" } #Target the latest platform features and APIs while also supporting older devices.
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
kotest = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mock" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

#build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinPlugin" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlinPlugin" }
ktlint-gradlePlugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlintGradlePlugin" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }


[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }


#Project plugins
redblackrepeat-hilt = { id = "redblackrepeat.hilt", version = "unspecified" }
redblackrepeat-android-aplication = { id = "redblackrepeat.android.application", version = "unspecified" }
redblackrepeat-android-aplication-compose = { id = "redblackrepeat.android.application.compose", version = "unspecified" }
redblackrepeat-ktlint = { id = "redblackrepeat.ktlint", version = "unspecified" }
redblackrepeat-android-library = { id = "redblackrepeat.android.library", version = "unspecified" }
redblackrepeat-android-feature = { id = "redblackrepeat.android.feature", version = "unspecified" }
redblackrepeat-android-library-compose = { id = "redblackrepeat.android.library.compose", version = "unspecified" }
redblackrepeat-unittest = { id = "redblackrepeat.unittest", version = "unspecified" }




