[versions]
minSdk = "26"
targetSdk = "34"
compileSdk = "34"
composeBom = "2024.09.00"
activityCompose = "1.9.2"
coreKtx = "1.13.1"
hiltAndroidCompiler = "2.51.1"
hiltAndroid = "2.51.1"
hiltNavigationCompose = "1.2.0"
junitJupiter = "5.10.2"
kotestRunnerJunit5 = "5.8.1"
androidxLifecycle = "2.8.5"
navigationCompose = "2.8.0"
roomVersion = "2.6.1"

androidGradlePlugin = "8.5.2"
kotlinPlugin = "2.0.0"
hiltPlugin = "2.51.1"
kspPlugin = "2.0.0-1.0.21"
jetbrainsKotlinJvm = "2.0.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" } #Access composable APIs built on top of Activity.
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" } # Fundamental components of compose UI needed to interact with the device, including layout, drawing, and input.
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" } #Target the latest platform features and APIs while also supporting older devices.
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotestRunnerJunit5" }

#build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinPlugin" }


[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

#Project plugins
redblackrepeat-hilt = { id = "redblackrepeat.hilt", version = "unspecified" }



