@file:Suppress("unused")

package com.pepekprodakshn.redblackrepeat.ui.theme

import androidx.compose.ui.graphics.Color

val BallRed = Color(0xFFff1908)
val BallYellow = Color(0xFFfffd15)
val BallGreen = Color(0xFF03be08)
val BallBrown = Color(0xFF9a6634)
val BallBlue = Color(0xFF0021fe)
val BallPink = Color(0xFFfc6387)
val BallBlack = Color(0xFF000000)

val md_theme_light_primary = Color(0xFF316B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB1F581)
val md_theme_light_onPrimaryContainer = Color(0xFF0A2000)
val md_theme_light_secondary = Color(0xFF944A00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC6)
val md_theme_light_onSecondaryContainer = Color(0xFF301400)
val md_theme_light_tertiary = Color(0xFF695F00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF5E568)
val md_theme_light_onTertiaryContainer = Color(0xFF201C00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFAFAF2)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF44483E)
val md_theme_light_inverseSurface = Color(0xFF2F312C)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
val md_theme_light_inversePrimary = Color(0xFF96D868)
val md_theme_light_surfaceTint = Color(0xFF316B00)
val md_theme_light_outlineVariant = Color(0xFFC4C8BB)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surfaceBright = Color(0xFFFAFAF2)
val md_theme_light_surfaceContainer = Color(0xFFEEEEE7)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9E8E1)
val md_theme_light_surfaceContainerHighest = Color(0xFFE3E3DC)
val md_theme_light_surfaceContainerLow = Color(0xFFF4F4ED)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceDim = Color(0xFFDADAD3)

val md_theme_dark_primary = Color(0xFF96D868)
val md_theme_dark_onPrimary = Color(0xFF163800)
val md_theme_dark_primaryContainer = Color(0xFF235100)
val md_theme_dark_onPrimaryContainer = Color(0xFFB1F581)
val md_theme_dark_secondary = Color(0xFFFFB784)
val md_theme_dark_onSecondary = Color(0xFF4F2500)
val md_theme_dark_secondaryContainer = Color(0xFF713700)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_tertiary = Color(0xFFD8C84F)
val md_theme_dark_onTertiary = Color(0xFF373100)
val md_theme_dark_tertiaryContainer = Color(0xFF4F4700)
val md_theme_dark_onTertiaryContainer = Color(0xFFF5E568)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF8E9286)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_surface = Color(0xFF121410)
val md_theme_dark_onSurface = Color(0xFFC7C7C0)
val md_theme_dark_surfaceVariant = Color(0xFF44483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inversePrimary = Color(0xFF316B00)
val md_theme_dark_surfaceTint = Color(0xFF96D868)
val md_theme_dark_outlineVariant = Color(0xFF44483E)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surfaceBright = Color(0xFF383A35)
val md_theme_dark_surfaceContainer = Color(0xFF1E201C)
val md_theme_dark_surfaceContainerHigh = Color(0xFF292B26)
val md_theme_dark_surfaceContainerHighest = Color(0xFF343531)
val md_theme_dark_surfaceContainerLow = Color(0xFF1A1C18)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0D0F0B)
val md_theme_dark_surfaceDim = Color(0xFF121410)

val seed = Color(0xFF443022)
val Red = Color(0xFFFF1908)
val yellow = Color(0xFFFFFD15)
val Green = Color(0xFF03BE08)
val brown = Color(0xFF9A6634)
val blue = Color(0xFF0021FE)
val pink = Color(0xFFFC6387)

val light_Red = Color(0xFFBF0800)
val light_onRed = Color(0xFFFFFFFF)
val light_RedContainer = Color(0xFFFFDAD4)
val light_onRedContainer = Color(0xFF400100)
val dark_Red = Color(0xFFFFB4A7)
val dark_onRed = Color(0xFF680200)
val dark_RedContainer = Color(0xFF920500)
val dark_onRedContainer = Color(0xFFFFDAD4)

val light_yellow = Color(0xFF626100)
val light_onyellow = Color(0xFFFFFFFF)
val light_yellowContainer = Color(0xFFEBEA00)
val light_onyellowContainer = Color(0xFF1D1D00)
val dark_yellow = Color(0xFFCECD00)
val dark_onyellow = Color(0xFF333200)
val dark_yellowContainer = Color(0xFF4A4900)
val dark_onyellowContainer = Color(0xFFEBEA00)

val light_Green = Color(0xFF006E01)
val light_onGreen = Color(0xFFFFFFFF)
val light_GreenContainer = Color(0xFF77FF62)
val light_onGreenContainer = Color(0xFF002200)
val dark_Green = Color(0xFF46E338)
val dark_onGreen = Color(0xFF003A00)
val dark_GreenContainer = Color(0xFF005301)
val dark_onGreenContainer = Color(0xFF77FF62)

val light_brown = Color(0xFF8D4F00)
val light_onbrown = Color(0xFFFFFFFF)
val light_brownContainer = Color(0xFFFFDCC0)
val light_onbrownContainer = Color(0xFF2D1600)
val dark_brown = Color(0xFFFFB876)
val dark_onbrown = Color(0xFF4B2700)
val dark_brownContainer = Color(0xFF6B3B00)
val dark_onbrownContainer = Color(0xFFFFDCC0)

val light_blue = Color(0xFF2B3FFF)
val light_onblue = Color(0xFFFFFFFF)
val light_blueContainer = Color(0xFFDFE0FF)
val light_onblueContainer = Color(0xFF000766)
val dark_blue = Color(0xFFBDC2FF)
val dark_onblue = Color(0xFF0011A1)
val dark_blueContainer = Color(0xFF001CE0)
val dark_onblueContainer = Color(0xFFDFE0FF)

val light_pink = Color(0xFFAF284F)
val light_onpink = Color(0xFFFFFFFF)
val light_pinkContainer = Color(0xFFFFD9DE)
val light_onpinkContainer = Color(0xFF400014)
val dark_pink = Color(0xFFFFB2BE)
val dark_onpink = Color(0xFF660026)
val dark_pinkContainer = Color(0xFF8E0739)
val dark_onpinkContainer = Color(0xFFFFD9DE)
